---
title: "R Notebook"
output: html_notebook
---
## Setup and load data
```{r}
pacman::p_load(quanteda, quanteda.textmodels, tidyverse, readr, ggplot2, rstatix, grid, gridExtra, viridis, ggsci, ggpubr, ragg)

pulled_manifestoes <- read_csv("data/CMP/pulled_manifestoes.csv")
lr_d2v <- read_csv("data/py_outputs/lr_d2v.csv",)
d2v_wf <- read_csv("data/py_outputs/d2v_wf.csv")
umap_s_embeds <- read_delim("results/arrays/umap_s_embeds.csv", col_names=c("umap_d1","umap_d2"), delim=" ")
umap_wf_embeds <- read_delim("results/arrays/umap_wf_embeds.csv", col_names=c("umap_d1","umap_d2"), delim=" ")
wf_cmp <- read_csv("results/arrays/wf_cmp.csv")
df_cmp <- read_csv("results/arrays/df_cmp.csv")


dr_valid <- read_csv("results/arrays/dr_valid_scores.csv")
pca_scaled <- read_delim("results/arrays/pca_scaled.csv", col_names=c("pca_d1","pca_d2"), delim=" ")
umap_s_scaled <- read_delim("results/arrays/umap_s_scaled.csv", col_names=c("umap_s_d1","umap_s_d2"), delim=" ")
umap_us_scaled <- read_delim("results/arrays/umap_us_scaled.csv", col_names=c("umap_us_d1","umap_us_d2"), delim=" ")
ae_scaled <- read_delim("results/arrays/ae_scaled.csv",col_names=c("ae_d1","ae_d2"), delim=" ")
ivis_scaled <- read_delim("results/arrays/ivis_scaled.csv",col_names=c("ivis_d1","ivis_d2"), delim=" ")
lda_scaled <- read_delim("results/arrays/lda_scaled.csv", col_names=c("lda_d1","lda_d2"), delim=" ")


pca_embeds <- read_delim("results/arrays/pca_embeds.csv", col_names=c("pca_d1","pca_d2"), delim=" ")
umap_s_embeds <- read_delim("results/arrays/umap_s_embeds.csv", col_names=c("umap_s_d1","umap_s_d2"), delim=" ")
umap_us_embeds <- read_delim("results/arrays/umap_us_embeds.csv", col_names=c("umap_us_d1","umap_us_d2"), delim=" ")
ae_embeds <- read_delim("results/arrays/ae_embeds.csv",col_names=c("ae_d1","ae_d2"), delim=" ")
ivis_embeds <- read_delim("results/arrays/ivis_embeds.csv",col_names=c("ivis_d1","ivis_d2"), delim=" ")
lda_embeds <- read_delim("results/arrays/lda_embeds.csv", col_names=c("lda_d1","lda_d2"), delim=" ")


trump_embeds <- read_delim("results/arrays/trump_embeds.csv",col_names=c("emb_d1","emb_d2"), delim=" ")
trump_scaled <- read_delim("results/arrays/trump_scaled.csv",col_names=c("emb_d1","emb_d2"), delim=" ")
trump_embeds_30 <- read_delim("results/arrays/trump_embeds_30.csv",col_names=c("emb_30_d1","emb_30_d2"), delim=" ")
trump_scaled_30 <- read_delim("results/arrays/trump_scaled_30.csv",col_names=c("emb_30_d1","emb_30_d2"), delim=" ")

trump_tweets <- read_csv("data/sins_tweets/MOTN_responses_groundtruth.csv")
```

## Wordfish scaling
```{r}


pulled_manifestoes$domain <- stringr::str_extract(string=as.character(pulled_manifestoes$code), pattern="[0-9]")

manifesto_deu <- pulled_manifestoes[which(pulled_manifestoes$country == "Germany"),]


grouped_texts <- manifesto_deu %>% 
    filter(!(code %in% c("H","000"))) %>%
    mutate(
        party_election = paste(party, election, sep="_"),
        party = case_when(
            grepl("Linke|Sozialismus", name) ~ "PDS/Die Linke",
            grepl("Sozialdemokratische", name) ~ "SPD",
            grepl("Christlich", name) ~ "CDU/CSU",
            grepl("Freie", name) ~ "FDP",
            grepl("Gr端nen", name) ~ "Die Gr端nen",
            grepl("Alternative", name) ~ "AfD",
            TRUE ~ NA_character_
        )
    ) %>%
    filter(!is.na(party)) %>%
    group_by(party, election) %>%
    summarise(
        text_new = paste(text, collapse = " "),
        num_speeches = n()
    )


dfmat <- corpus(grouped_texts, text_field = "text_new") %>%
             tokens(remove_punct = TRUE, remove_numbers = TRUE, remove_symbols = TRUE) %>%
             tokens_remove(stopwords("de")) %>%
             dfm() %>%
             dfm_trim(min_termfreq = 50, verbose = TRUE, min_docfreq = 0.03, docfreq_type = "prop") %>%
             dfm_subset(ntoken(.) > 0, drop_docid = TRUE)

wf_mod <- quanteda.textmodels::textmodel_wordfish(dfmat, dispersion = "poisson", 
                                 sparse = TRUE)
results <- grouped_texts %>% select(-text_new)

results$wf_score <- wf_mod$theta
results$wf_sd <- wf_mod$se.theta



```


## Merge datasets

```{r}
lr_d2v <- lr_d2v %>% separate("party_election", sep="\\_", into = c("party", "election")) %>%
    mutate(election = as.numeric(election))

df <-  df_cmp %>%
    left_join(results, by = c("party", "election")) %>% 
    left_join(lr_d2v, by = c("party", "election")) %>% 
    bind_cols(umap_s_embeds)

```




## Figure 2
```{r figure 1}
plot_wf <- ggplot(data = df,
                  aes(x=factor(election), y=wf_score, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, linewidth = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("Wordfish")


plot_d2v1 <- ggplot(data = df,
                  aes(x=factor(election), y= d2v_d1, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("Doc2Vec - Dim 1")

plot_d2v2 <- ggplot(data = df,
                  aes(x=factor(election), y= d2v_d2, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("Doc2Vec - Dim 2")


plot_tf1 <- ggplot(data = df,
                  aes(x=factor(election), y=umap_d1, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("TFScale - Dim 1")


plot_tf2 <- ggplot(data = df,
                  aes(x=factor(election), y=umap_d2, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("TFScale - Dim 2")

plot_cmplog <- ggplot(data = df,
                  aes(x=factor(election), y=lr_log, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("CMP - Log")




library(ragg)
library(ggpubr)
figure_1 <- ggarrange(plot_tf1, plot_wf, plot_d2v1, plot_tf2, plot_cmplog, plot_d2v2,
                      common.legend = TRUE)

agg_png(filename = here::here("results","tabs and figs","figure 1.png"), res = 360, width = 4800, height = 3200)
figure_1
invisible(dev.off())



```

## Correlation table
```{r}
cor_table <- df %>% cor_test(vars = "lr_log", vars2=c("umap_d1", "wf_score", "d2v_d1", "umap_d2", "d2v_d2"))

cor_table <- round(cor_table[,c("cor", "p")], 2)
library(gt)


```


## Wordfish - Welfare

```{r env}

manifesto_wf = manifesto_deu[which(manifesto_deu$code %in% c("504", "505")),]
grouped_texts <- manifesto_wf %>% 
    mutate(
        party_election = paste(party, election, sep="_"),
        party = case_when(
            grepl("Linke|Sozialismus", name) ~ "PDS/Die Linke",
            grepl("Sozialdemokratische", name) ~ "SPD",
            grepl("Christlich", name) ~ "CDU/CSU",
            grepl("Freie", name) ~ "FDP",
            grepl("Gr端nen", name) ~ "Die Gr端nen",
            grepl("Alternative", name) ~ "AfD",
            TRUE ~ NA_character_
        )
    ) %>%
    filter(!is.na(party)) %>%
    group_by(party, election) %>%
    summarise(
        text_new = paste(text, collapse = " "),
        num_speeches = n()
    )
dfmat <- corpus(grouped_texts, text_field = "text_new") %>%
             tokens(remove_punct = TRUE, remove_numbers = TRUE, remove_symbols = TRUE) %>%
             tokens_remove(stopwords("de")) %>%
             dfm() %>%
             dfm_trim(min_termfreq = 50, verbose = TRUE, min_docfreq = 0.03, docfreq_type = "prop") %>%
             dfm_subset(ntoken(.) > 0, drop_docid = TRUE)

wf_mod <- quanteda.textmodels::textmodel_wordfish(dfmat, dispersion = "poisson", 
                                 sparse = TRUE)
results <- grouped_texts %>% select(-text_new)

results$wf_score <- wf_mod$theta
results$wf_sd <- wf_mod$sd_theta

## Merge datasets

d2v_wf  <- d2v_wf %>% separate("party_election", sep="\\_", into = c("party", "election")) %>%
    mutate(election = as.numeric(election))

df_wf <-  wf_cmp %>%
    left_join(results, by = c("party", "election")) %>% 
    left_join(d2v_wf, by = c("party", "election")) %>% 
    bind_cols(umap_wf_embeds)

```
## Figure 3

```{r figure 2}
plot_wf <- ggplot(data = df_wf,
                  aes(x=factor(election), y=wf_score, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, linewidth = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("Wordfish")


plot_d2v1 <- ggplot(data = df_wf,
                  aes(x=factor(election), y= d2v_d1, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("Doc2Vec - Dim 1")



plot_tf1 <- ggplot(data = df_wf,
                  aes(x=factor(election), y=umap_d1, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("TFScale - Dim 1")




plot_cmplog <- ggplot(data = df_wf,
                  aes(x=factor(election), y=lr_log, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("CMP - Log")

plot_cmpabs <- ggplot(data = df_wf,
                  aes(x=factor(election), y=lr_abs, color=party,group=party)) +
    geom_point() +
    geom_line(alpha=0.5, size = 1) + 
    scale_color_manual(name = "Party",  
                       values = c("blue","black", "green","yellow", "purple", "red")) +
    theme(axis.title = element_text(size = 15),legend.title = element_text(size = 15), legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold")) +
    xlab("Election") +
    ylab("CMP - Org")


legend_2 <- get_legend(plot_tf1)
figure_2 <- ggarrange(plot_tf1, plot_wf, plot_d2v1, plot_cmplog, plot_cmpabs, as_ggplot(legend_2),
                      legend="none")
agg_png(filename = here::here("results","tabs and figs","figure 2.png"), res = 360, width = 4800, height = 3200)
figure_2
invisible(dev.off())


```

## Figure 4

```{r}
lr_log <- df_cmp[,"lr_log"]
df_scaled <- bind_cols(pca_scaled, umap_s_scaled, umap_us_scaled, ivis_scaled, lda_scaled, ae_scaled)
cor_table_2 <- df_scaled %>% cor_test(vars = "pca_d1", vars2=c("pca_d1","umap_s_d1", "umap_us_d1", "ivis_d1", "lda_d1", "ae_d1"))
cor_2 <- abs(cor_table_2["cor"])
df_embeds <- bind_cols(pca_embeds, umap_s_embeds, umap_us_embeds, ivis_embeds, lda_embeds, ae_embeds, lr_log)
cor_table_3 <- df_embeds %>% cor_test(vars = "lr_log", vars2=c("pca_d1","umap_s_d1", "umap_us_d1", "ivis_d1", "lda_d1", "ae_d1"))
cor_3 <- abs(cor_table_3["cor"])

df_dr <- bind_cols(dr_valid, cor_2, cor_3)
colnames(df_dr) <- c("techniques","tw","sil","cor_pca", "cor_cmp")

plot_tw <- ggplot(data = df_dr,
                  aes(x=techniques, y=tw, fill = techniques)) +
    geom_bar(stat="identity") +
    scale_fill_viridis(name = "Techniques",  
                       labels = c("Autoencoders", "Ivis", "LDA", "PCA",
                                  "UMAP - Supervised","UMAP - Unsupervised"),
                      discrete = TRUE) +
    theme(axis.title.y = element_text(size = 15),legend.title = element_text(size = 15), 
          legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold"),
          axis.text.x=element_blank(), axis.ticks.x=element_blank()
          ) +
    xlab("Trustworthiness") +
    ylab("Coefficients")

plot_sil <- ggplot(data = df_dr,
                  aes(x=techniques, y=sil, fill = techniques)) +
    geom_bar(stat="identity") +
    scale_fill_viridis(name = "Techniques",   
                       labels = c("Autoencoders", "Ivis", "LDA", "PCA",
                                  "UMAP - Supervised","UMAP - Unsupervised"), discrete=TRUE) +
    theme(axis.title.y = element_text(size = 15),legend.title = element_text(size = 15), 
          legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold"),
          axis.text.x=element_blank(), axis.ticks.x=element_blank()
          ) +
    xlab("Silhouette scores") +
    ylab("Coefficients")

plot_corpca <- ggplot(data = df_dr,
                  aes(x=techniques, y=cor_pca, fill = techniques)) +
    geom_bar(stat="identity") +
    scale_fill_viridis(name = "Techniques",  
                       labels = c("Autoencoders", "Ivis", "LDA", "PCA",
                                  "UMAP - Supervised","UMAP - Unsupervised"), discrete=TRUE) +
    theme(axis.title.y = element_text(size = 15),legend.title = element_text(size = 15), 
          legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold"),
          axis.text.x=element_blank(), axis.ticks.x=element_blank()
          ) +
    xlab("Absolute Correlation to PCA embeddings") +
    ylab("Coefficients")

plot_corcmp <- ggplot(data = df_dr,
                  aes(x=techniques, y=cor_cmp, fill = techniques)) +
    geom_bar(stat="identity") +
    scale_fill_viridis(name = "Techniques",  
                       labels = c("Autoencoders", "Ivis", "LDA", "PCA",
                                  "UMAP - Supervised","UMAP - Unsupervised"), discrete=TRUE) +
    theme(axis.title.y = element_text(size = 15),legend.title = element_text(size = 15), 
          legend.text = element_text(size = 14), title =  element_text(size = 18, face = "bold"),
          axis.text.x=element_blank(), axis.ticks.x=element_blank()
          ) +
    xlab("Absolute Correlation to CMP log scores") +
    ylab("Coefficients")


figure_3 <- ggarrange(plot_tw, plot_sil, plot_corpca, plot_corcmp, 
                      common.legend=TRUE)
agg_png(filename = here::here("results","tabs and figs","figure 3.png"), res = 360, width = 4800, height = 3200)
figure_3
invisible(dev.off())

```


## Correlation - hypothetical tests
```{r}


```



## Figure 5
```{r}
ideo <- c("Conservative", "Liberal", "Moderate", "Not sure",
          "Very conservative", "Very liberal")

trump_embeds_agg <- trump_embeds %>%
    bind_cols(trump_embeds_30) %>%
    mutate(ideo5=ideo) %>%
    filter(ideo5 != "Not sure")

df_trump <- trump_scaled %>%
    bind_cols(trump_scaled_30) %>%
    mutate(ideo5=trump_tweets$ideo5) %>%
    filter(ideo5 != "Not sure")

plot_ideo <- ggplot(data = df_trump,
                  aes(x=emb_d1, y=emb_d2, 
                      color = factor(ideo5))) +
    geom_point(alpha=0.3) +
    geom_point(data=trump_embeds_agg, size = 6) +
    scale_color_viridis(name = "Objective Political Ideology", 
                        discrete = TRUE) +
    theme(axis.title.y = element_text(size = 15),
          legend.title = element_text(size = 15), 
          legend.text = element_text(size = 14), 
          title =  element_text(size = 18, face = "bold"),
          axis.title.x = element_text(size = 15)
          ) +
    xlab("First dimension") +
    ylab("Second dimension") +
    labs(title = "100% known stances")
plot_ideo_30 <- ggplot(data = df_trump,
                  aes(x=emb_30_d1, y=emb_30_d2, 
                      color = factor(ideo5))) +
    geom_point(alpha=0.3) +
    geom_point(data=trump_embeds_agg, size = 6) +
    scale_color_viridis(name = "Objective Political Ideology",
                        discrete = TRUE) +
    theme(axis.title.y = element_text(size = 15),
          legend.title = element_text(size = 15), 
          legend.text = element_text(size = 14), 
          title =  element_text(size = 18, face = "bold"),
          axis.title.x = element_text(size = 15)
          ) +
    xlab("First dimension") +
    ylab("Second dimension") + 
    labs(title = "30% known stances + CMP transferred")

figure_5 <- ggarrange(plot_ideo, plot_ideo_30, 
                      common.legend=TRUE)
agg_png(filename = here::here("results","tabs and figs","figure 5.png"), res = 360, width = 4800, height = 3200)
figure_5
invisible(dev.off())


```


