---
title: "Plenarprotokoll_Extracting speeches"
output: html_notebook
---





```{r setup}
pacman::p_load("quanteda", "XML","xml2", "knitr", "stringr", "here", "dplyr","purrr")
```





### Get the main directory and set up a paste function. Note: Due to formating reasons, can't use the package readtext to read XML files.

```{r message = FALSE}
lwd <- here::here("data", "GermaParl") 

```

### Create a file list for each voting period?
```{r message = FALSE}
bundeslist <- c("13","14","15","16", "17","18")

for (i in bundeslist){
  plelist <- paste0("ple",i)
  plelistn <- paste0("plelist",i)
  assign(plelist, setNames(list.files(path= paste(lwd,i, sep = "/"), pattern = ".xml"), plelistn))
}

```



### Now read the files and put them all into a big dataframe. Repeat the chunk (modify wd) for each dataframe.


```{r message = FALSE}
xml_to_df <- function(file_path){
    speech_list <- list()
    speaker_list <- list()
    role_list <- list()
    party_list <- list()
    position_list <- list()
    doc <- read_xml(file_path)
    agendas <- xml_find_all(doc, "//div")
    speakers <- xml_find_all(agendas,"//sp")
    date <- xml_text(xml_find_all(doc,"//date")[1])
    session_num <- xml_text(xml_find_all(doc,"//sessionNo"))
    for (i in 1:length(speakers)){
        speech <- xml_text(xml_find_all(speakers[i], ".//p"))
        speaker <- rep(xml_attr(speakers[i],"name"), length(speech))
        role <- rep(xml_attr(speakers[i],"role"), length(speech))
        party <- rep(xml_attr(speakers[i],"party"), length(speech))
        position <- rep(xml_attr(speakers[i],"position"), length(speech))
        speaker_list <- c(speaker_list, speaker)
        role_list <- c(role_list, role)
        party_list <- c(party_list, party)
        position_list <- c(position_list, position)
        speech_list <- c(speech_list, speech)
    }
    df <- data.frame(cbind(unlist(speaker_list), unlist(role_list), unlist(party_list), unlist(position_list), unlist(speech_list)))
    df <- df %>% 
        mutate(
            speaker = gsub("[[:space:]]","", X1),
            role = X2,
            party = X3,
            position = X4, 
            text = X5,
            session = rep(session_num, nrow(df)),
            date = rep(date, nrow(df))
            
        ) %>%
        filter(role != "presidency") 
    
    return(df)
}
### 

iter_xml <- function(folder, bundestag,filelist){
    df_final <- data.frame()
    for (i in 1:length(filelist)){
        file_path <- paste(folder, bundestag, filelist[i], sep="/")
        df_temp <- xml_to_df(file_path)
        df_final <- rbind(df_final, df_temp)
    }
    df_final <- df_final %>%
        mutate(
            bundestag = bundestag,
            year = format(as.Date(date), format="%Y")
        )
    return(df_final)
}

###

folder <- here::here("data", "GermaParl")

df13 <- iter_xml(folder, 13, ple13)
df14 <- iter_xml(folder, 14, ple14)
df15 <- iter_xml(folder, 15, ple15)
df16 <- iter_xml(folder, 16, ple16)
df17 <- iter_xml(folder, 17, ple17)
df18 <- iter_xml(folder, 18, ple18)

## The 191th Sitzung is problematic
df18 <- df18 %>%
    mutate(
        session = case_when(
            grepl("191", session) ~ 191,
            TRUE ~ as.numeric(session)
        )
    )

```


## Merge dfs and clean a little bit
```{r merge}
## Merge all dataframes 
df <- rbind(df13, df14, df15, df16, df17, df18)
df <- df %>%
  select(-X1,-X2,-X3,-X4,-X5)


## Remove noisy texts (mainly from the 191th Sitzung)
df$text <- str_remove_all(df$text, "\\([^)]*\\[*\\]:[^)]*\\)")
df$text <- str_remove_all(df$text, "\\(.{0,25}Beifall[^)]*\\)")
df$text <- str_remove_all(df$text, "\\<U*\\>")

df <- df %>%
  mutate(
      party = case_when(
          grepl("(?i)Linke|PDS", party) ~ "DIE LINKE", ## case insensitive
          grepl("(?i)GRÜNE", party) ~ "BÜNDNIS 90/DIE GRÜNEN",
          grepl("[SPD\\s]{3,6}$", party) ~ "SPD",
          grepl("FDP", party) ~ "FDP",
          grepl("CDU|CSU", party) ~ "CDU/CSU",
          TRUE ~ "Unknown"
      )
  ) %>%
  filter(!(party %in% c("Unknown")))

df <- df %>%
  mutate(
      date = case_when(
          bundestag == 15 & session == 78 ~ "2003-11-26",
          TRUE ~ as.character(date)
      ),
      year = format(as.Date(date), format = "%Y")
  )


write.csv(df, file = here::here("data", "outputs", "germaparl.csv"), row.names = FALSE, fileEncoding = "UTF-8")
```











