#!/usr/bin/env bash
# =============================================================================
# clean.sh — Remove all pipeline-generated outputs from ContextScale
#
# Keeps intact:
#   data/CMP/               — raw CMP manifesto metadata
#   data/coalitionagree/    — raw coalition agreement texts
#   data/MOTN/              — raw Twitter ground-truth datasets
#   results/models/         — pre-trained model weights (.safetensors)
#   manifesto_apikey.txt    — user's API key
#
# Deletes (generated by the pipeline):
#   data/r_outputs/*        — Steps 1, 2 and 4 outputs
#   data/py_outputs/*       — Step 3 outputs
#   results/classification results/*  — classification metric CSVs
#   results/datasets/*      — final scaled datasets
#   results/tabs and figs/* — paper figures and tables
#
# Usage:
#   bash scripts/clean.sh           # dry-run (lists what would be deleted)
#   bash scripts/clean.sh --confirm  # actually delete
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY_RUN=true

for arg in "$@"; do
  case "$arg" in
    --confirm) DRY_RUN=false ;;
    -h|--help)
      echo "Usage: bash scripts/clean.sh [--confirm]"
      echo "  --confirm   Actually delete files (omit for a dry-run preview)"
      exit 0 ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

if $DRY_RUN; then
  echo "=== DRY-RUN — no files will be deleted. Pass --confirm to delete. ==="
  echo ""
fi

# ── helper: list or delete a glob/directory ──────────────────────────────────
do_clean() {
  local description="$1"; shift
  # Remaining args are paths (may contain globs)
  echo "  [$description]"
  for target in "$@"; do
    if compgen -G "$target" > /dev/null 2>&1 || [ -e "$target" ]; then
      for f in $target; do
        echo "    $f"
        if ! $DRY_RUN; then
          rm -rf "$f"
        fi
      done
    else
      echo "    (nothing to clean)"
    fi
  done
}

cd "$REPO_ROOT"

echo "=== Step 1 & 2 outputs (data/r_outputs) ==="
do_clean "manifesto corpus CSVs" \
  "data/r_outputs/pulled_manifestoes.csv" \
  "data/r_outputs/pulled_manifestoes_test.csv"
do_clean "coalition agreement CSVs" \
  "data/r_outputs/coalitionagree_texts.csv"

echo ""
echo "=== Step 4 outputs (Wordfish, data/r_outputs) ==="
do_clean "Wordfish CSVs" \
  "data/r_outputs/wf_ep.csv" \
  "data/r_outputs/wf_gen_all_countries.csv" \
  "data/r_outputs/wf_topic_all_countries.csv" \
  "data/r_outputs/wf_tw.csv" \
  "data/r_outputs/wf_welfare.csv"

echo ""
echo "=== Step 3 outputs (data/py_outputs) ==="
do_clean "Python outputs" "data/py_outputs"/*  2>/dev/null || true

echo ""
echo "=== Report outputs (results/) ==="
do_clean "Classification metrics" "results/classification results"/*  2>/dev/null || true
do_clean "Scaled datasets"         "results/datasets"/*               2>/dev/null || true
do_clean "Figures and tables"      "results/tabs and figs"/*          2>/dev/null || true

echo ""
if $DRY_RUN; then
  echo "=== Dry-run complete. Run with --confirm to delete these files. ==="
else
  echo "=== Cleanup complete. ==="
fi
