#!/usr/bin/env bash
# =============================================================================
# replicate.sh — End-to-end replication script for ContextScale
#
# Runs the full pipeline in order: 01 → 02 → 03a → 03b → 04 → 05
#   Step 1  (R)       01_manifesto_pull.Rmd   — pull manifesto corpus
#   Step 2  (R)       02_r_prep.Rmd           — coalition agreement prep
#   Step 3a (Python)  03a_main_analyses.ipynb  — main model training / inference
#   Step 3b (Python)  03b_ablation_study.ipynb — ablation study (optional; long)
#   Step 4  (R)       04_r_prep.Rmd           — Wordfish benchmarks
#   Step 5  (R)       05_visualizations.Rmd   — all figures and tables
#
# Modes (mutually exclusive; default is full pipeline):
#   --figures-only    Run Step 5 only (05_visualizations.Rmd).
#                     Requires all prior outputs to already exist.
#   (default)         Run the full pipeline: Steps 1 → 2 → 3 → 4 → 5.
#
# Options:
#   --skip-env        Skip Python environment creation/activation
#   --skip-r-install  Skip R package installation (renv::restore)
#   --skip-ablation   Skip Step 3b (ablation study)
#   --venv            Use pip + virtualenv instead of Conda (default: Conda)
#   --tmux [NAME]     Launch (or attach to) a named tmux session and run there.
#                     Default session name: contextscale-rep
#                     Prints attach/detach commands and exits if session is new.
#   --help/-h         Show this message
#
# Pre-requisites:
#   • conda (Miniconda/Anaconda) OR python3.11 + virtualenv for --venv
#   • R (≥4.4) with renv installed, or R packages installed manually
#   • Manifesto API key in manifesto_apikey.txt  (required for Step 1)
#
# Outputs — generated by the pipeline:
#   data/r_outputs/   Steps 1, 2, 4
#   data/py_outputs/  Step 3
#   results/classification results/
#   results/datasets/
#   results/tabs and figs/
# =============================================================================

set -euo pipefail

# ── defaults ─────────────────────────────────────────────────────────────────
SKIP_ENV=false
SKIP_R_INSTALL=false
SKIP_ABLATION=false
USE_VENV=false
USE_TMUX=false
FIGURES_ONLY=false
TMUX_SESSION="contextscale-rep"
CONDA_ENV_NAME="contextscale"
VENV_DIR=".venv"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOG_DIR="${REPO_ROOT}/logs"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${LOG_DIR}/replicate_${TIMESTAMP}.log"

# ── argument parsing ─────────────────────────────────────────────────────────
PASSTHROUGH_ARGS=()   # all flags except --tmux, forwarded when re-launching
ARGS=("$@")
for (( i=0; i<${#ARGS[@]}; i++ )); do
  arg="${ARGS[$i]}"
  case "$arg" in
    --figures-only)    FIGURES_ONLY=true;    PASSTHROUGH_ARGS+=("$arg") ;;
    --skip-env)        SKIP_ENV=true;        PASSTHROUGH_ARGS+=("$arg") ;;
    --skip-r-install)  SKIP_R_INSTALL=true;  PASSTHROUGH_ARGS+=("$arg") ;;
    --skip-ablation)   SKIP_ABLATION=true;   PASSTHROUGH_ARGS+=("$arg") ;;
    --venv)            USE_VENV=true;        PASSTHROUGH_ARGS+=("$arg") ;;
    --tmux)
      USE_TMUX=true
      # Optional next argument is the session name (if it doesn't start with --)
      next="${ARGS[$((i+1))]:-}"
      if [[ -n "$next" && "$next" != --* ]]; then
        TMUX_SESSION="$next"
        (( i++ ))
      fi
      ;;
    -h|--help)
      sed -n '2,/^# ====/p' "$0" | grep '^#' | sed 's/^# \?//'
      exit 0 ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

# ── tmux re-launch ────────────────────────────────────────────────────────────
# If --tmux was requested and we are NOT already inside a tmux session,
# create (or report on) the named session and run this script inside it.
if $USE_TMUX && [ -z "${TMUX:-}" ]; then
  if ! command -v tmux &>/dev/null; then
    echo "tmux not found. Install it (e.g. 'sudo apt install tmux') or run without --tmux."
    exit 1
  fi

  mkdir -p "${REPO_ROOT}/logs"
  SCRIPT_ABS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/replicate.sh"

  if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "tmux session '$TMUX_SESSION' already exists."
    echo ""
    echo "  Attach:  tmux attach-session -t $TMUX_SESSION"
    echo "  Detach:  Ctrl-B  then  D"
    echo ""
    echo "To start a fresh run, kill the existing session first:"
    echo "  tmux kill-session -t $TMUX_SESSION"
    exit 0
  fi

  INNER_CMD="cd '${REPO_ROOT}' && bash '${SCRIPT_ABS}' ${PASSTHROUGH_ARGS[*]:-}; echo ''; echo '=== Pipeline finished. Press Enter to close. ==='; read"

  echo "Launching pipeline in tmux session '$TMUX_SESSION'..."
  tmux new-session -d -s "$TMUX_SESSION" -x 220 -y 50 "bash -c \"${INNER_CMD}\""

  echo ""
  echo "  Session:  $TMUX_SESSION"
  echo "  Attach:   tmux attach-session -t $TMUX_SESSION"
  echo "  Detach:   Ctrl-B  then  D   (while attached)"
  echo "  Kill:     tmux kill-session -t $TMUX_SESSION"
  echo ""
  echo "  Follow log (once pipeline starts):"
  echo "    tail -f ${LOG_DIR}/replicate_*.log"
  exit 0
fi

# ── helpers ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}[$(date +%H:%M:%S)]${NC} $*" | tee -a "$LOG_FILE"; }
ok()   { echo -e "${GREEN}[$(date +%H:%M:%S)] ✓ $*${NC}" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}[$(date +%H:%M:%S)] ⚠ $*${NC}" | tee -a "$LOG_FILE"; }
die()  { echo -e "${RED}[$(date +%H:%M:%S)] ✗ $*${NC}" | tee -a "$LOG_FILE"; exit 1; }

mkdir -p "$LOG_DIR"
cd "$REPO_ROOT"

if $FIGURES_ONLY; then
  PIPELINE_MODE="Figures-Only (Step 5)"
else
  PIPELINE_MODE="Full Replication Pipeline"
fi

echo "========================================================================" | tee "$LOG_FILE"
echo " ContextScale — ${PIPELINE_MODE}" | tee -a "$LOG_FILE"
echo " Started:  $(date)" | tee -a "$LOG_FILE"
echo " Log file: $LOG_FILE" | tee -a "$LOG_FILE"
echo "========================================================================" | tee -a "$LOG_FILE"

# ── Check prerequisites ───────────────────────────────────────────────────────
if [ ! -f "manifesto_apikey.txt" ]; then
  warn "manifesto_apikey.txt not found."
  warn "Step 1 will attempt to pull the manifesto corpus from the CMP API."
  warn "If you do not have an API key, place the pre-generated CSVs from Dataverse at:"
  warn "  data/r_outputs/pulled_manifestoes.csv"
  warn "  data/r_outputs/pulled_manifestoes_test.csv"
  warn "and re-run with Step 1 output files already present — the Rmd will skip the API call."
fi

# Note: Notebooks require pre-trained weights in results/models/ (inference-only by design)
if [ ! -d "results/models/ensemble" ] && ! $FIGURES_ONLY; then
  warn "results/models/ensemble/ not found.
Download pre-trained weights from Dataverse and unzip into results/models/ first."
fi

# ── Step 0: Create output directories ────────────────────────────────────────
log "Creating output directories..."
mkdir -p data/r_outputs \
         data/py_outputs \
         "results/classification results" \
         results/datasets \
         "results/tabs and figs"
ok "Output directories ready."

# ── Step 0a: Python environment setup ─────────────────────────────────────────
if ! $SKIP_ENV && ! $FIGURES_ONLY; then
  log "Setting up Python environment..."

  if $USE_VENV; then
    # ── pip + virtualenv ──────────────────────────────────────────────────────
    if ! command -v python3.11 &>/dev/null; then
      die "python3.11 not found. Install Python 3.11 or use Conda (remove --venv flag)."
    fi
    if [ ! -d "$VENV_DIR" ]; then
      log "Creating virtualenv at $VENV_DIR..."
      python3.11 -m venv "$VENV_DIR" | tee -a "$LOG_FILE"
    fi
    # shellcheck disable=SC1091
    source "${VENV_DIR}/bin/activate"
    log "Installing Python packages from requirements.txt..."
    pip install --upgrade pip 2>&1 | tail -3 | tee -a "$LOG_FILE"
    pip install -r requirements.txt 2>&1 | tee -a "$LOG_FILE"
    PYTHON_CMD="${VENV_DIR}/bin/python"
    JUPYTER_CMD="${VENV_DIR}/bin/jupyter"
    ok "Virtualenv environment ready."

  else
    # ── Conda ─────────────────────────────────────────────────────────────────
    if ! command -v conda &>/dev/null; then
      die "conda not found. Install Miniconda/Anaconda, or pass --venv to use virtualenv."
    fi
    # Initialise conda for this non-interactive shell
    eval "$(conda shell.bash hook)" 2>/dev/null || true

    if conda env list | grep -q "^${CONDA_ENV_NAME}[[:space:]]"; then
      log "Conda environment '${CONDA_ENV_NAME}' already exists — activating."
    else
      log "Creating conda environment '${CONDA_ENV_NAME}' from environment.yml..."
      conda env create -f environment.yml 2>&1 | tee -a "$LOG_FILE"
      ok "Conda environment created."
    fi
    conda activate "$CONDA_ENV_NAME"
    PYTHON_CMD="python"
    JUPYTER_CMD="jupyter"
    ok "Conda environment '${CONDA_ENV_NAME}' activated."
  fi

  # Ensure critical packages are available
  log "Ensuring jupyter and nbconvert are installed..."
  $PYTHON_CMD -m pip install --upgrade jupyter nbconvert 2>&1 | tail -3 | tee -a "$LOG_FILE"
  ok "Critical packages installed."

  # Post-install language data
  log "Downloading spaCy and NLTK language data..."
  $PYTHON_CMD -m spacy download en_core_web_sm 2>&1 | tee -a "$LOG_FILE" || warn "spaCy model download failed — may already be installed."
  $PYTHON_CMD -c "import nltk; nltk.download('stopwords', quiet=True)" 2>&1 | tee -a "$LOG_FILE"
  ok "Language data ready."

else
  if $FIGURES_ONLY; then
    log "Skipping Python environment setup (--figures-only)."
  else
    log "Skipping Python environment setup (--skip-env)."
  fi
  PYTHON_CMD="${PYTHON_CMD:-python}"
  JUPYTER_CMD="${JUPYTER_CMD:-jupyter}"
fi

# ── Step 0b: R package setup ─────────────────────────────────────────────────
if ! $SKIP_R_INSTALL; then
  log "Restoring R packages via renv..."
  if ! command -v Rscript &>/dev/null; then
    die "Rscript not found. Install R (≥4.4) before running this script."
  fi
  if [ -f "renv.lock" ]; then
    Rscript -e "
      if (!requireNamespace('renv', quietly=TRUE)) install.packages('renv', repos='https://cloud.r-project.org')
      renv::restore(prompt=FALSE)
    " 2>&1 | tee -a "$LOG_FILE"
    ok "R packages restored from renv.lock."
  else
    warn "renv.lock not found — installing R packages manually via pacman."
    Rscript -e "
      if (!requireNamespace('pacman', quietly=TRUE)) install.packages('pacman', repos='https://cloud.r-project.org')
      pacman::p_load(tidyverse, manifestoR, quanteda, quanteda.textmodels,
                     ggplot2, viridis, ggsci, ggpubr, ragg, scales, gt,
                     rstatix, gridExtra, openxlsx, countrycode, scico, caret,
                     ggExtra, rempsyc, flextable, magrittr, grid, readr, dplyr,
                     rmarkdown, knitr)
    " 2>&1 | tee -a "$LOG_FILE"
    ok "R packages installed."
  fi
else
  log "Skipping R package installation (--skip-r-install)."
fi

# ── Utility: run an Rmd file ─────────────────────────────────────────────────
run_rmd() {
  local step="$1"; local file="$2"
  log "=== $step: $file ==="
  Rscript -e "rmarkdown::render('${file}', quiet=FALSE)" 2>&1 | tee -a "$LOG_FILE"
  ok "$step complete."
}

run_python_notebook() {
  local step="$1"; local file="$2"
  log "=== $step: $file ==="

  # Notebooks are inference-only by design; they load pre-trained weights from results/models/
  # To train models, use: python train.py --num_models 5 --epochs 5
  
  $JUPYTER_CMD nbconvert --to notebook --execute --inplace \
    --ExecutePreprocessor.timeout=86400 \
    "$file" 2>&1 | tee -a "$LOG_FILE"

  ok "$step complete."
}

if ! $FIGURES_ONLY; then

# ── Step 1: Pull manifesto data ───────────────────────────────────────────────
run_rmd "Step 1" "01_manifesto_pull.Rmd"

# ── Step 2: R preparation (coalition agreements) ───────────────────────
run_rmd "Step 2" "02_r_prep.Rmd"

# ── Step 3a + 3b: Main analyses and ablation (Python notebooks) ─────────────
run_python_notebook "Step 3a" "03a_main_analyses.ipynb"

if $SKIP_ABLATION; then
  log "Skipping Step 3b (--skip-ablation)."
else
  run_python_notebook "Step 3b" "03b_ablation_study.ipynb"
fi

# ── Step 4: Wordfish benchmarks ───────────────────────────────────────────────
run_rmd "Step 4" "04_r_prep.Rmd"

else
  log "--figures-only: skipping Steps 1–4."
fi  # end of full-pipeline block

# ── Step 5: Visualizations ────────────────────────────────────────────────────
run_rmd "Step 5" "05_visualizations.Rmd"

# ── Summary ───────────────────────────────────────────────────────────────────
echo "" | tee -a "$LOG_FILE"
echo "========================================================================" | tee -a "$LOG_FILE"
echo " ${PIPELINE_MODE} complete!  $(date)" | tee -a "$LOG_FILE"
echo "========================================================================" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo " Key outputs:" | tee -a "$LOG_FILE"
echo "   results/tabs and figs/       — all paper figures and tables" | tee -a "$LOG_FILE"
echo "   results/datasets/            — final party position datasets" | tee -a "$LOG_FILE"
echo "   results/classification results/ — classification metric CSVs" | tee -a "$LOG_FILE"
echo "   data/py_outputs/             — intermediate Python outputs" | tee -a "$LOG_FILE"
echo "   data/r_outputs/              — intermediate R outputs" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo " Full log saved to: $LOG_FILE" | tee -a "$LOG_FILE"
